package:
  name: py3-pandas
  version: 2.1.3
  epoch: 1
  description: Tests for py3-pandas
  copyright:
    - license: 'BSD-3-Clause'

pipeline:

test:
  environment:
    contents:
      packages:
        - busybox
        - python-3
  pipeline:
    - runs: |
        python3 ./py3-pandas-test.py
