package:
  name: bar
  version: 1.2.3.4
  epoch: 0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - build-base
      - wolfi-base

# transform the version 1.2.3.4 to 1.2.3+4
var-transforms:
  - from: ${{package.version}}
    match: \.(\d+)$
    replace: +$1
    to: mangled-package-version

pipeline:
  # use the new mangled-package-version variable
  - uses: fetch
    with:
      uri: https://github.com/foo/bar/archive/refs/tags/${{vars.mangled-package-version}}.tar.gz
