package:
  name: hello
  version: 2.12.4
  epoch: 0
  description: "an example of how conditionals influence build behavior"
  copyright:
    - license: Not-Applicable

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox

vars:
  foo: "Hello"
  bar: "World"
  buildLocation: "/home/build/foo"

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: short-package-version

pipeline:
  # Variable substitution works for `with`, `working-directory` and
  # `runs` statements.
  - working-directory: ${{vars.buildLocation}}
    runs: |
      echo "current working directory: $(pwd)"

  - working-directory: ${{targets.destdir}}
    runs: |
      echo "${{vars.foo}} ${{vars.bar}}"

subpackages:
  - name: subpackage-${{vars.short-package-version}}
    pipeline:
      - runs: echo "subpackage-${{vars.short-package-version}}"
