package:
  name: melange
  version: 0.0.1
  epoch: 0
  description: "a cloud-native packaging build system"
  copyright:
    - attestation: |
        Copyright 2022 Chainguard, Inc.
      license: Apache-2.0
  dependencies:
    runtime:
      - bubblewrap

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - busybox
      - make
      - go
      - git
      - ca-certificates-bundle

pipeline:
  - uses: autoconf/make-install
